export const paikkakunnat = [
{"kuntakoodi":"020","nimi_fi":"Akaa","nimi_se":"Akaa","maakunta":"Pirkanmaa","seutukunta":"Etelä-Pirkanmaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"005","nimi_fi":"Alajärvi","nimi_se":"Alajärvi","maakunta":"Etelä-Pohjanmaa","seutukunta":"Järviseudun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"009","nimi_fi":"Alavieska","nimi_se":"Alavieska","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Ylivieskan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"010","nimi_fi":"Alavus","nimi_se":"Alavus","maakunta":"Etelä-Pohjanmaa","seutukunta":"Kuusiokuntien","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"016","nimi_fi":"Asikkala","nimi_se":"Asikkala","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"018","nimi_fi":"Askola","nimi_se":"Askola","maakunta":"Uusimaa","seutukunta":"Porvoon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"019","nimi_fi":"Aura","nimi_se":"Aura","maakunta":"Varsinais-Suomi","seutukunta":"Loimaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"035","nimi_fi":"Brändö","nimi_se":"Brändö","maakunta":"Ahvenanmaa","seutukunta":"Ålands skärgård","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"043","nimi_fi":"Eckerö","nimi_se":"Eckerö","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"046","nimi_fi":"Enonkoski","nimi_se":"Enonkoski","maakunta":"Etelä-Savo","seutukunta":"Savonlinnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"047","nimi_fi":"Enontekiö","nimi_se":"Enontekis","maakunta":"Lappi","seutukunta":"Tunturi-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"049","nimi_fi":"Espoo","nimi_se":"Esbo","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"050","nimi_fi":"Eura","nimi_se":"Eura","maakunta":"Satakunta","seutukunta":"Rauman","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"051","nimi_fi":"Eurajoki","nimi_se":"Euraåminne","maakunta":"Satakunta","seutukunta":"Rauman","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"052","nimi_fi":"Evijärvi","nimi_se":"Evijärvi","maakunta":"Etelä-Pohjanmaa","seutukunta":"Järviseudun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"060","nimi_fi":"Finström","nimi_se":"Finström","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"061","nimi_fi":"Forssa","nimi_se":"Forssa","maakunta":"Kanta-Häme","seutukunta":"Forssan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"062","nimi_fi":"Föglö","nimi_se":"Föglö","maakunta":"Ahvenanmaa","seutukunta":"Ålands skärgård","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"065","nimi_fi":"Geta","nimi_se":"Geta","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"069","nimi_fi":"Haapajärvi","nimi_se":"Haapajärvi","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Nivala-Haapajärven","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"071","nimi_fi":"Haapavesi","nimi_se":"Haapavesi","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Haapaveden-Siikalatvan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"072","nimi_fi":"Hailuoto","nimi_se":"Karlö","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"074","nimi_fi":"Halsua","nimi_se":"Halsua","maakunta":"Keski-Pohjanmaa","seutukunta":"Kaustisen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"075","nimi_fi":"Hamina","nimi_se":"Fredrikshamn","maakunta":"Kymenlaakso","seutukunta":"Kotka-Haminan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"076","nimi_fi":"Hammarland","nimi_se":"Hammarland","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"077","nimi_fi":"Hankasalmi","nimi_se":"Hankasalmi","maakunta":"Keski-Suomi","seutukunta":"Jyväskylän","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"078","nimi_fi":"Hanko","nimi_se":"Hangö","maakunta":"Uusimaa","seutukunta":"Raaseporin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"079","nimi_fi":"Harjavalta","nimi_se":"Harjavalta","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"081","nimi_fi":"Hartola","nimi_se":"Hartola","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"082","nimi_fi":"Hattula","nimi_se":"Hattula","maakunta":"Kanta-Häme","seutukunta":"Hämeenlinnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"086","nimi_fi":"Hausjärvi","nimi_se":"Hausjärvi","maakunta":"Kanta-Häme","seutukunta":"Riihimäen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"111","nimi_fi":"Heinola","nimi_se":"Heinola","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"090","nimi_fi":"Heinävesi","nimi_se":"Heinävesi","maakunta":"Etelä-Savo","seutukunta":"Savonlinnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"091","nimi_fi":"Helsinki","nimi_se":"Helsingfors","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"097","nimi_fi":"Hirvensalmi","nimi_se":"Hirvensalmi","maakunta":"Etelä-Savo","seutukunta":"Mikkelin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"098","nimi_fi":"Hollola","nimi_se":"Hollola","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"099","nimi_fi":"Honkajoki","nimi_se":"Honkajoki","maakunta":"Satakunta","seutukunta":"Pohjois-Satakunnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"102","nimi_fi":"Huittinen","nimi_se":"Huittinen","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"103","nimi_fi":"Humppila","nimi_se":"Humppila","maakunta":"Kanta-Häme","seutukunta":"Forssan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"105","nimi_fi":"Hyrynsalmi","nimi_se":"Hyrynsalmi","maakunta":"Kainuu","seutukunta":"Kehys-Kainuun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"106","nimi_fi":"Hyvinkää","nimi_se":"Hyvinge","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"283","nimi_fi":"Hämeenkoski","nimi_se":"Hämeenkoski","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"108","nimi_fi":"Hämeenkyrö","nimi_se":"Tavastkyro","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"109","nimi_fi":"Hämeenlinna","nimi_se":"Tavastehus","maakunta":"Kanta-Häme","seutukunta":"Hämeenlinnan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"139","nimi_fi":"Ii","nimi_se":"Ii","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulunkaaren","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"140","nimi_fi":"Iisalmi","nimi_se":"Idensalmi","maakunta":"Pohjois-Savo","seutukunta":"Ylä-Savon","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"142","nimi_fi":"Iitti","nimi_se":"Iitti","maakunta":"Kymenlaakso","seutukunta":"Kouvolan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"143","nimi_fi":"Ikaalinen","nimi_se":"Ikalis","maakunta":"Pirkanmaa","seutukunta":"Luoteis-Pirkanmaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"145","nimi_fi":"Ilmajoki","nimi_se":"Ilmajoki","maakunta":"Etelä-Pohjanmaa","seutukunta":"Seinäjoen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"146","nimi_fi":"Ilomantsi","nimi_se":"Ilomants","maakunta":"Pohjois-Karjala","seutukunta":"Joensuun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"153","nimi_fi":"Imatra","nimi_se":"Imatra","maakunta":"Etelä-Karjala","seutukunta":"Imatran","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"148","nimi_fi":"Inari","nimi_se":"Enare","maakunta":"Lappi","seutukunta":"Pohjois-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"149","nimi_fi":"Inkoo","nimi_se":"Ingå","maakunta":"Uusimaa","seutukunta":"Raaseporin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"151","nimi_fi":"Isojoki","nimi_se":"Storå","maakunta":"Etelä-Pohjanmaa","seutukunta":"Suupohjan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"152","nimi_fi":"Isokyrö","nimi_se":"Storkyro","maakunta":"Pohjanmaa","seutukunta":"Kyrönmaa","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"164","nimi_fi":"Jalasjärvi","nimi_se":"Jalasjärvi","maakunta":"Etelä-Pohjanmaa","seutukunta":"Seinäjoen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"165","nimi_fi":"Janakkala","nimi_se":"Janakkala","maakunta":"Kanta-Häme","seutukunta":"Hämeenlinnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"167","nimi_fi":"Joensuu","nimi_se":"Joensuu","maakunta":"Pohjois-Karjala","seutukunta":"Joensuun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"169","nimi_fi":"Jokioinen","nimi_se":"Jockis","maakunta":"Kanta-Häme","seutukunta":"Forssan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"170","nimi_fi":"Jomala","nimi_se":"Jomala","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"171","nimi_fi":"Joroinen","nimi_se":"Jorois","maakunta":"Etelä-Savo","seutukunta":"Pieksämäen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"172","nimi_fi":"Joutsa","nimi_se":"Joutsa","maakunta":"Keski-Suomi","seutukunta":"Joutsan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"174","nimi_fi":"Juankoski","nimi_se":"Juankoski","maakunta":"Pohjois-Savo","seutukunta":"Koillis-Savon","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"176","nimi_fi":"Juuka","nimi_se":"Juuka","maakunta":"Pohjois-Karjala","seutukunta":"Joensuun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"177","nimi_fi":"Juupajoki","nimi_se":"Juupajoki","maakunta":"Pirkanmaa","seutukunta":"Ylä-Pirkanmaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"178","nimi_fi":"Juva","nimi_se":"Juva","maakunta":"Etelä-Savo","seutukunta":"Pieksämäen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"179","nimi_fi":"Jyväskylä","nimi_se":"Jyväskylä","maakunta":"Keski-Suomi","seutukunta":"Jyväskylän","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"181","nimi_fi":"Jämijärvi","nimi_se":"Jämijärvi","maakunta":"Satakunta","seutukunta":"Pohjois-Satakunnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"182","nimi_fi":"Jämsä","nimi_se":"Jämsä","maakunta":"Keski-Suomi","seutukunta":"Jämsän","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"186","nimi_fi":"Järvenpää","nimi_se":"Träskända","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"202","nimi_fi":"Kaarina","nimi_se":"S:t Karins","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"204","nimi_fi":"Kaavi","nimi_se":"Kaavi","maakunta":"Pohjois-Savo","seutukunta":"Koillis-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"205","nimi_fi":"Kajaani","nimi_se":"Kajana","maakunta":"Kainuu","seutukunta":"Kajaanin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"208","nimi_fi":"Kalajoki","nimi_se":"Kalajoki","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Ylivieskan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"211","nimi_fi":"Kangasala","nimi_se":"Kangasala","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"213","nimi_fi":"Kangasniemi","nimi_se":"Kangasniemi","maakunta":"Etelä-Savo","seutukunta":"Mikkelin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"214","nimi_fi":"Kankaanpää","nimi_se":"Kankaanpää","maakunta":"Satakunta","seutukunta":"Pohjois-Satakunnan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"216","nimi_fi":"Kannonkoski","nimi_se":"Kannonkoski","maakunta":"Keski-Suomi","seutukunta":"Saarijärven-Viitasaaren","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"217","nimi_fi":"Kannus","nimi_se":"Kannus","maakunta":"Keski-Pohjanmaa","seutukunta":"Kokkolan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"218","nimi_fi":"Karijoki","nimi_se":"Bötom","maakunta":"Etelä-Pohjanmaa","seutukunta":"Suupohjan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"224","nimi_fi":"Karkkila","nimi_se":"Högfors","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"226","nimi_fi":"Karstula","nimi_se":"Karstula","maakunta":"Keski-Suomi","seutukunta":"Saarijärven-Viitasaaren","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"230","nimi_fi":"Karvia","nimi_se":"Karvia","maakunta":"Satakunta","seutukunta":"Pohjois-Satakunnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"231","nimi_fi":"Kaskinen","nimi_se":"Kaskö","maakunta":"Pohjanmaa","seutukunta":"Sydösterbottens kustregion","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"232","nimi_fi":"Kauhajoki","nimi_se":"Kauhajoki","maakunta":"Etelä-Pohjanmaa","seutukunta":"Suupohjan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"233","nimi_fi":"Kauhava","nimi_se":"Kauhava","maakunta":"Etelä-Pohjanmaa","seutukunta":"Seinäjoen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"235","nimi_fi":"Kauniainen","nimi_se":"Grankulla","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"236","nimi_fi":"Kaustinen","nimi_se":"Kaustby","maakunta":"Keski-Pohjanmaa","seutukunta":"Kaustisen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"239","nimi_fi":"Keitele","nimi_se":"Keitele","maakunta":"Pohjois-Savo","seutukunta":"Ylä-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"240","nimi_fi":"Kemi","nimi_se":"Kemi","maakunta":"Lappi","seutukunta":"Kemi-Tornion","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"320","nimi_fi":"Kemijärvi","nimi_se":"Kemijärvi","maakunta":"Lappi","seutukunta":"Itä-Lapin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"241","nimi_fi":"Keminmaa","nimi_se":"Keminmaa","maakunta":"Lappi","seutukunta":"Kemi-Tornion","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"322","nimi_fi":"Kemiönsaari","nimi_se":"Kimitoön","maakunta":"Varsinais-Suomi","seutukunta":"Åboland-Turunmaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"244","nimi_fi":"Kempele","nimi_se":"Kempele","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"245","nimi_fi":"Kerava","nimi_se":"Kervo","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"249","nimi_fi":"Keuruu","nimi_se":"Keuruu","maakunta":"Keski-Suomi","seutukunta":"Keuruun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"250","nimi_fi":"Kihniö","nimi_se":"Kihniö","maakunta":"Pirkanmaa","seutukunta":"Luoteis-Pirkanmaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"256","nimi_fi":"Kinnula","nimi_se":"Kinnula","maakunta":"Keski-Suomi","seutukunta":"Saarijärven-Viitasaaren","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"257","nimi_fi":"Kirkkonummi","nimi_se":"Kyrkslätt","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"260","nimi_fi":"Kitee","nimi_se":"Kitee","maakunta":"Pohjois-Karjala","seutukunta":"Keski-Karjalan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"261","nimi_fi":"Kittilä","nimi_se":"Kittilä","maakunta":"Lappi","seutukunta":"Tunturi-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"263","nimi_fi":"Kiuruvesi","nimi_se":"Kiuruvesi","maakunta":"Pohjois-Savo","seutukunta":"Ylä-Savon","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"265","nimi_fi":"Kivijärvi","nimi_se":"Kivijärvi","maakunta":"Keski-Suomi","seutukunta":"Saarijärven-Viitasaaren","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"271","nimi_fi":"Kokemäki","nimi_se":"Kumo","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"272","nimi_fi":"Kokkola","nimi_se":"Karleby","maakunta":"Keski-Pohjanmaa","seutukunta":"Kokkolan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"273","nimi_fi":"Kolari","nimi_se":"Kolari","maakunta":"Lappi","seutukunta":"Tunturi-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"275","nimi_fi":"Konnevesi","nimi_se":"Konnevesi","maakunta":"Keski-Suomi","seutukunta":"Äänekosken","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"276","nimi_fi":"Kontiolahti","nimi_se":"Kontiolahti","maakunta":"Pohjois-Karjala","seutukunta":"Joensuun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"280","nimi_fi":"Korsnäs","nimi_se":"Korsnäs","maakunta":"Pohjanmaa","seutukunta":"Vaasan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"284","nimi_fi":"Koski Tl","nimi_se":"Koski Tl","maakunta":"Varsinais-Suomi","seutukunta":"Loimaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"285","nimi_fi":"Kotka","nimi_se":"Kotka","maakunta":"Kymenlaakso","seutukunta":"Kotka-Haminan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"286","nimi_fi":"Kouvola","nimi_se":"Kouvola","maakunta":"Kymenlaakso","seutukunta":"Kouvolan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"287","nimi_fi":"Kristiinankaupunki","nimi_se":"Kristinestad","maakunta":"Pohjanmaa","seutukunta":"Sydösterbottens kustregion","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"288","nimi_fi":"Kruunupyy","nimi_se":"Kronoby","maakunta":"Pohjanmaa","seutukunta":"Jakobstadsregionen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"290","nimi_fi":"Kuhmo","nimi_se":"Kuhmo","maakunta":"Kainuu","seutukunta":"Kehys-Kainuun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"291","nimi_fi":"Kuhmoinen","nimi_se":"Kuhmoinen","maakunta":"Keski-Suomi","seutukunta":"Jämsän","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"295","nimi_fi":"Kumlinge","nimi_se":"Kumlinge","maakunta":"Ahvenanmaa","seutukunta":"Ålands skärgård","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"297","nimi_fi":"Kuopio","nimi_se":"Kuopio","maakunta":"Pohjois-Savo","seutukunta":"Kuopion","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"300","nimi_fi":"Kuortane","nimi_se":"Kuortane","maakunta":"Etelä-Pohjanmaa","seutukunta":"Kuusiokuntien","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"301","nimi_fi":"Kurikka","nimi_se":"Kurikka","maakunta":"Etelä-Pohjanmaa","seutukunta":"Seinäjoen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"304","nimi_fi":"Kustavi","nimi_se":"Gustavs","maakunta":"Varsinais-Suomi","seutukunta":"Vakka-Suomen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"305","nimi_fi":"Kuusamo","nimi_se":"Kuusamo","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Koillismaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"312","nimi_fi":"Kyyjärvi","nimi_se":"Kyyjärvi","maakunta":"Keski-Suomi","seutukunta":"Saarijärven-Viitasaaren","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"316","nimi_fi":"Kärkölä","nimi_se":"Kärkölä","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"317","nimi_fi":"Kärsämäki","nimi_se":"Kärsämäki","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Nivala-Haapajärven","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"318","nimi_fi":"Kökar","nimi_se":"Kökar","maakunta":"Ahvenanmaa","seutukunta":"Ålands skärgård","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"319","nimi_fi":"Köyliö","nimi_se":"Kjulo","maakunta":"Satakunta","seutukunta":"Rauman","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"398","nimi_fi":"Lahti","nimi_se":"Lahtis","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"399","nimi_fi":"Laihia","nimi_se":"Laihela","maakunta":"Pohjanmaa","seutukunta":"Kyrönmaa","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"400","nimi_fi":"Laitila","nimi_se":"Laitila","maakunta":"Varsinais-Suomi","seutukunta":"Vakka-Suomen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"407","nimi_fi":"Lapinjärvi","nimi_se":"Lappträsk","maakunta":"Uusimaa","seutukunta":"Loviisan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"402","nimi_fi":"Lapinlahti","nimi_se":"Lapinlahti","maakunta":"Pohjois-Savo","seutukunta":"Ylä-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"403","nimi_fi":"Lappajärvi","nimi_se":"Lappajärvi","maakunta":"Etelä-Pohjanmaa","seutukunta":"Järviseudun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"405","nimi_fi":"Lappeenranta","nimi_se":"Villmanstrand","maakunta":"Etelä-Karjala","seutukunta":"Lappeenrannan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"408","nimi_fi":"Lapua","nimi_se":"Lappo","maakunta":"Etelä-Pohjanmaa","seutukunta":"Seinäjoen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"410","nimi_fi":"Laukaa","nimi_se":"Laukaa","maakunta":"Keski-Suomi","seutukunta":"Jyväskylän","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"413","nimi_fi":"Lavia","nimi_se":"Lavia","maakunta":"Satakunta","seutukunta":"Pohjois-Satakunnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"416","nimi_fi":"Lemi","nimi_se":"Lemi","maakunta":"Etelä-Karjala","seutukunta":"Lappeenrannan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"417","nimi_fi":"Lemland","nimi_se":"Lemland","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"418","nimi_fi":"Lempäälä","nimi_se":"Lempäälä","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"420","nimi_fi":"Leppävirta","nimi_se":"Leppävirta","maakunta":"Pohjois-Savo","seutukunta":"Varkauden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"421","nimi_fi":"Lestijärvi","nimi_se":"Lestijärvi","maakunta":"Keski-Pohjanmaa","seutukunta":"Kaustisen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"422","nimi_fi":"Lieksa","nimi_se":"Lieksa","maakunta":"Pohjois-Karjala","seutukunta":"Pielisen-Karjalan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"423","nimi_fi":"Lieto","nimi_se":"Lundo","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"425","nimi_fi":"Liminka","nimi_se":"Limingo","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"426","nimi_fi":"Liperi","nimi_se":"Liperi","maakunta":"Pohjois-Karjala","seutukunta":"Joensuun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"444","nimi_fi":"Lohja","nimi_se":"Lojo","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"430","nimi_fi":"Loimaa","nimi_se":"Loimaa","maakunta":"Varsinais-Suomi","seutukunta":"Loimaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"433","nimi_fi":"Loppi","nimi_se":"Loppi","maakunta":"Kanta-Häme","seutukunta":"Riihimäen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"434","nimi_fi":"Loviisa","nimi_se":"Lovisa","maakunta":"Uusimaa","seutukunta":"Loviisan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"435","nimi_fi":"Luhanka","nimi_se":"Luhanka","maakunta":"Keski-Suomi","seutukunta":"Joutsan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"436","nimi_fi":"Lumijoki","nimi_se":"Lumijoki","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"438","nimi_fi":"Lumparland","nimi_se":"Lumparland","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"440","nimi_fi":"Luoto","nimi_se":"Larsmo","maakunta":"Pohjanmaa","seutukunta":"Jakobstadsregionen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"441","nimi_fi":"Luumäki","nimi_se":"Luumäki","maakunta":"Etelä-Karjala","seutukunta":"Lappeenrannan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"442","nimi_fi":"Luvia","nimi_se":"Luvia","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"475","nimi_fi":"Maalahti","nimi_se":"Malax","maakunta":"Pohjanmaa","seutukunta":"Vaasan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"476","nimi_fi":"Maaninka","nimi_se":"Maaninka","maakunta":"Pohjois-Savo","seutukunta":"Kuopion","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"478","nimi_fi":"Maarianhamina","nimi_se":"Mariehamn","maakunta":"Ahvenanmaa","seutukunta":"Mariehamns stad","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"480","nimi_fi":"Marttila","nimi_se":"Marttila","maakunta":"Varsinais-Suomi","seutukunta":"Loimaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"481","nimi_fi":"Masku","nimi_se":"Masku","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"483","nimi_fi":"Merijärvi","nimi_se":"Merijärvi","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Ylivieskan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"484","nimi_fi":"Merikarvia","nimi_se":"Sastmola","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"489","nimi_fi":"Miehikkälä","nimi_se":"Miehikkälä","maakunta":"Kymenlaakso","seutukunta":"Kotka-Haminan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"491","nimi_fi":"Mikkeli","nimi_se":"S:t Michel","maakunta":"Etelä-Savo","seutukunta":"Mikkelin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"494","nimi_fi":"Muhos","nimi_se":"Muhos","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"495","nimi_fi":"Multia","nimi_se":"Multia","maakunta":"Keski-Suomi","seutukunta":"Keuruun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"498","nimi_fi":"Muonio","nimi_se":"Muonio","maakunta":"Lappi","seutukunta":"Tunturi-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"499","nimi_fi":"Mustasaari","nimi_se":"Korsholm","maakunta":"Pohjanmaa","seutukunta":"Vaasan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"500","nimi_fi":"Muurame","nimi_se":"Muurame","maakunta":"Keski-Suomi","seutukunta":"Jyväskylän","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"503","nimi_fi":"Mynämäki","nimi_se":"Mynämäki","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"504","nimi_fi":"Myrskylä","nimi_se":"Mörskom","maakunta":"Uusimaa","seutukunta":"Porvoon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"505","nimi_fi":"Mäntsälä","nimi_se":"Mäntsälä","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"508","nimi_fi":"Mänttä-Vilppula","nimi_se":"Mänttä-Vilppula","maakunta":"Pirkanmaa","seutukunta":"Ylä-Pirkanmaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"507","nimi_fi":"Mäntyharju","nimi_se":"Mäntyharju","maakunta":"Etelä-Savo","seutukunta":"Mikkelin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"529","nimi_fi":"Naantali","nimi_se":"Nådendal","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"531","nimi_fi":"Nakkila","nimi_se":"Nakkila","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"532","nimi_fi":"Nastola","nimi_se":"Nastola","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"535","nimi_fi":"Nivala","nimi_se":"Nivala","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Nivala-Haapajärven","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"536","nimi_fi":"Nokia","nimi_se":"Nokia","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"538","nimi_fi":"Nousiainen","nimi_se":"Nousis","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"541","nimi_fi":"Nurmes","nimi_se":"Nurmes","maakunta":"Pohjois-Karjala","seutukunta":"Pielisen-Karjalan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"543","nimi_fi":"Nurmijärvi","nimi_se":"Nurmijärvi","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"545","nimi_fi":"Närpiö","nimi_se":"Närpes","maakunta":"Pohjanmaa","seutukunta":"Sydösterbottens kustregion","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"560","nimi_fi":"Orimattila","nimi_se":"Orimattila","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"561","nimi_fi":"Oripää","nimi_se":"Oripää","maakunta":"Varsinais-Suomi","seutukunta":"Loimaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"562","nimi_fi":"Orivesi","nimi_se":"Orivesi","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"563","nimi_fi":"Oulainen","nimi_se":"Oulainen","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Ylivieskan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"564","nimi_fi":"Oulu","nimi_se":"Uleåborg","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"309","nimi_fi":"Outokumpu","nimi_se":"Outokumpu","maakunta":"Pohjois-Karjala","seutukunta":"Joensuun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"576","nimi_fi":"Padasjoki","nimi_se":"Padasjoki","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"577","nimi_fi":"Paimio","nimi_se":"Pemar","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"578","nimi_fi":"Paltamo","nimi_se":"Paltamo","maakunta":"Kainuu","seutukunta":"Kajaanin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"445","nimi_fi":"Parainen","nimi_se":"Pargas","maakunta":"Varsinais-Suomi","seutukunta":"Åboland-Turunmaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"580","nimi_fi":"Parikkala","nimi_se":"Parikkala","maakunta":"Etelä-Karjala","seutukunta":"Imatran","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"581","nimi_fi":"Parkano","nimi_se":"Parkano","maakunta":"Pirkanmaa","seutukunta":"Luoteis-Pirkanmaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"599","nimi_fi":"Pedersören kunta","nimi_se":"Pedersöre","maakunta":"Pohjanmaa","seutukunta":"Jakobstadsregionen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"583","nimi_fi":"Pelkosenniemi","nimi_se":"Pelkosenniemi","maakunta":"Lappi","seutukunta":"Itä-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"854","nimi_fi":"Pello","nimi_se":"Pello","maakunta":"Lappi","seutukunta":"Torniolaakson","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"584","nimi_fi":"Perho","nimi_se":"Perho","maakunta":"Keski-Pohjanmaa","seutukunta":"Kaustisen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"588","nimi_fi":"Pertunmaa","nimi_se":"Pertunmaa","maakunta":"Etelä-Savo","seutukunta":"Mikkelin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"592","nimi_fi":"Petäjävesi","nimi_se":"Petäjävesi","maakunta":"Keski-Suomi","seutukunta":"Jyväskylän","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"593","nimi_fi":"Pieksämäki","nimi_se":"Pieksämäki","maakunta":"Etelä-Savo","seutukunta":"Pieksämäen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"595","nimi_fi":"Pielavesi","nimi_se":"Pielavesi","maakunta":"Pohjois-Savo","seutukunta":"Ylä-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"598","nimi_fi":"Pietarsaari","nimi_se":"Jakobstad","maakunta":"Pohjanmaa","seutukunta":"Jakobstadsregionen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"601","nimi_fi":"Pihtipudas","nimi_se":"Pihtipudas","maakunta":"Keski-Suomi","seutukunta":"Saarijärven-Viitasaaren","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"604","nimi_fi":"Pirkkala","nimi_se":"Birkala","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"607","nimi_fi":"Polvijärvi","nimi_se":"Polvijärvi","maakunta":"Pohjois-Karjala","seutukunta":"Joensuun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"608","nimi_fi":"Pomarkku","nimi_se":"Påmark","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"609","nimi_fi":"Pori","nimi_se":"Björneborg","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"611","nimi_fi":"Pornainen","nimi_se":"Borgnäs","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"638","nimi_fi":"Porvoo","nimi_se":"Borgå","maakunta":"Uusimaa","seutukunta":"Porvoon","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"614","nimi_fi":"Posio","nimi_se":"Posio","maakunta":"Lappi","seutukunta":"Itä-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"615","nimi_fi":"Pudasjärvi","nimi_se":"Pudasjärvi","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulunkaaren","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"616","nimi_fi":"Pukkila","nimi_se":"Pukkila","maakunta":"Uusimaa","seutukunta":"Porvoon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"619","nimi_fi":"Punkalaidun","nimi_se":"Punkalaidun","maakunta":"Pirkanmaa","seutukunta":"Lounais-Pirkanmaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"620","nimi_fi":"Puolanka","nimi_se":"Puolanka","maakunta":"Kainuu","seutukunta":"Kehys-Kainuun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"623","nimi_fi":"Puumala","nimi_se":"Puumala","maakunta":"Etelä-Savo","seutukunta":"Mikkelin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"624","nimi_fi":"Pyhtää","nimi_se":"Pyttis","maakunta":"Kymenlaakso","seutukunta":"Kotka-Haminan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"625","nimi_fi":"Pyhäjoki","nimi_se":"Pyhäjoki","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Raahen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"626","nimi_fi":"Pyhäjärvi","nimi_se":"Pyhäjärvi","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Nivala-Haapajärven","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"630","nimi_fi":"Pyhäntä","nimi_se":"Pyhäntä","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Haapaveden-Siikalatvan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"631","nimi_fi":"Pyhäranta","nimi_se":"Pyhäranta","maakunta":"Varsinais-Suomi","seutukunta":"Vakka-Suomen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"635","nimi_fi":"Pälkäne","nimi_se":"Pälkäne","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"636","nimi_fi":"Pöytyä","nimi_se":"Pöytyä","maakunta":"Varsinais-Suomi","seutukunta":"Loimaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"678","nimi_fi":"Raahe","nimi_se":"Brahestad","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Raahen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"710","nimi_fi":"Raasepori","nimi_se":"Raseborg","maakunta":"Uusimaa","seutukunta":"Raaseporin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"680","nimi_fi":"Raisio","nimi_se":"Reso","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"681","nimi_fi":"Rantasalmi","nimi_se":"Rantasalmi","maakunta":"Etelä-Savo","seutukunta":"Savonlinnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"683","nimi_fi":"Ranua","nimi_se":"Ranua","maakunta":"Lappi","seutukunta":"Rovaniemen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"684","nimi_fi":"Rauma","nimi_se":"Raumo","maakunta":"Satakunta","seutukunta":"Rauman","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"686","nimi_fi":"Rautalampi","nimi_se":"Rautalampi","maakunta":"Pohjois-Savo","seutukunta":"Sisä-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"687","nimi_fi":"Rautavaara","nimi_se":"Rautavaara","maakunta":"Pohjois-Savo","seutukunta":"Koillis-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"689","nimi_fi":"Rautjärvi","nimi_se":"Rautjärvi","maakunta":"Etelä-Karjala","seutukunta":"Imatran","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"691","nimi_fi":"Reisjärvi","nimi_se":"Reisjärvi","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Nivala-Haapajärven","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"694","nimi_fi":"Riihimäki","nimi_se":"Riihimäki","maakunta":"Kanta-Häme","seutukunta":"Riihimäen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"697","nimi_fi":"Ristijärvi","nimi_se":"Ristijärvi","maakunta":"Kainuu","seutukunta":"Kajaanin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"698","nimi_fi":"Rovaniemi","nimi_se":"Rovaniemi","maakunta":"Lappi","seutukunta":"Rovaniemen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"700","nimi_fi":"Ruokolahti","nimi_se":"Ruokolahti","maakunta":"Etelä-Karjala","seutukunta":"Imatran","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"702","nimi_fi":"Ruovesi","nimi_se":"Ruovesi","maakunta":"Pirkanmaa","seutukunta":"Ylä-Pirkanmaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"704","nimi_fi":"Rusko","nimi_se":"Rusko","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"707","nimi_fi":"Rääkkylä","nimi_se":"Rääkkylä","maakunta":"Pohjois-Karjala","seutukunta":"Keski-Karjalan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"729","nimi_fi":"Saarijärvi","nimi_se":"Saarijärvi","maakunta":"Keski-Suomi","seutukunta":"Saarijärven-Viitasaaren","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"732","nimi_fi":"Salla","nimi_se":"Salla","maakunta":"Lappi","seutukunta":"Itä-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"734","nimi_fi":"Salo","nimi_se":"Salo","maakunta":"Varsinais-Suomi","seutukunta":"Salon","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"736","nimi_fi":"Saltvik","nimi_se":"Saltvik","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"790","nimi_fi":"Sastamala","nimi_se":"Sastamala","maakunta":"Pirkanmaa","seutukunta":"Lounais-Pirkanmaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"738","nimi_fi":"Sauvo","nimi_se":"Sagu","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"739","nimi_fi":"Savitaipale","nimi_se":"Savitaipale","maakunta":"Etelä-Karjala","seutukunta":"Lappeenrannan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"740","nimi_fi":"Savonlinna","nimi_se":"Nyslott","maakunta":"Etelä-Savo","seutukunta":"Savonlinnan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"742","nimi_fi":"Savukoski","nimi_se":"Savukoski","maakunta":"Lappi","seutukunta":"Itä-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"743","nimi_fi":"Seinäjoki","nimi_se":"Seinäjoki","maakunta":"Etelä-Pohjanmaa","seutukunta":"Seinäjoen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"746","nimi_fi":"Sievi","nimi_se":"Sievi","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Ylivieskan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"747","nimi_fi":"Siikainen","nimi_se":"Siikainen","maakunta":"Satakunta","seutukunta":"Pohjois-Satakunnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"748","nimi_fi":"Siikajoki","nimi_se":"Siikajoki","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Raahen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"791","nimi_fi":"Siikalatva","nimi_se":"Siikalatva","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Haapaveden-Siikalatvan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"749","nimi_fi":"Siilinjärvi","nimi_se":"Siilinjärvi","maakunta":"Pohjois-Savo","seutukunta":"Kuopion","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"751","nimi_fi":"Simo","nimi_se":"Simo","maakunta":"Lappi","seutukunta":"Kemi-Tornion","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"753","nimi_fi":"Sipoo","nimi_se":"Sibbo","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"755","nimi_fi":"Siuntio","nimi_se":"Sjundeå","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"758","nimi_fi":"Sodankylä","nimi_se":"Sodankylä","maakunta":"Lappi","seutukunta":"Pohjois-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"759","nimi_fi":"Soini","nimi_se":"Soini","maakunta":"Etelä-Pohjanmaa","seutukunta":"Järviseudun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"761","nimi_fi":"Somero","nimi_se":"Somero","maakunta":"Varsinais-Suomi","seutukunta":"Salon","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"762","nimi_fi":"Sonkajärvi","nimi_se":"Sonkajärvi","maakunta":"Pohjois-Savo","seutukunta":"Ylä-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"765","nimi_fi":"Sotkamo","nimi_se":"Sotkamo","maakunta":"Kainuu","seutukunta":"Kajaanin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"766","nimi_fi":"Sottunga","nimi_se":"Sottunga","maakunta":"Ahvenanmaa","seutukunta":"Ålands skärgård","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"768","nimi_fi":"Sulkava","nimi_se":"Sulkava","maakunta":"Etelä-Savo","seutukunta":"Savonlinnan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"771","nimi_fi":"Sund","nimi_se":"Sund","maakunta":"Ahvenanmaa","seutukunta":"Ålands landsbygd","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"777","nimi_fi":"Suomussalmi","nimi_se":"Suomussalmi","maakunta":"Kainuu","seutukunta":"Kehys-Kainuun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"778","nimi_fi":"Suonenjoki","nimi_se":"Suonenjoki","maakunta":"Pohjois-Savo","seutukunta":"Sisä-Savon","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"781","nimi_fi":"Sysmä","nimi_se":"Sysmä","maakunta":"Päijät-Häme","seutukunta":"Lahden","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"783","nimi_fi":"Säkylä","nimi_se":"Säkylä","maakunta":"Satakunta","seutukunta":"Rauman","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"831","nimi_fi":"Taipalsaari","nimi_se":"Taipalsaari","maakunta":"Etelä-Karjala","seutukunta":"Lappeenrannan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"832","nimi_fi":"Taivalkoski","nimi_se":"Taivalkoski","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Koillismaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"833","nimi_fi":"Taivassalo","nimi_se":"Tövsala","maakunta":"Varsinais-Suomi","seutukunta":"Vakka-Suomen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"834","nimi_fi":"Tammela","nimi_se":"Tammela","maakunta":"Kanta-Häme","seutukunta":"Forssan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"837","nimi_fi":"Tampere","nimi_se":"Tammerfors","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"838","nimi_fi":"Tarvasjoki","nimi_se":"Tarvasjoki","maakunta":"Varsinais-Suomi","seutukunta":"Loimaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"844","nimi_fi":"Tervo","nimi_se":"Tervo","maakunta":"Pohjois-Savo","seutukunta":"Sisä-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"845","nimi_fi":"Tervola","nimi_se":"Tervola","maakunta":"Lappi","seutukunta":"Kemi-Tornion","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"846","nimi_fi":"Teuva","nimi_se":"Östermark","maakunta":"Etelä-Pohjanmaa","seutukunta":"Suupohjan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"848","nimi_fi":"Tohmajärvi","nimi_se":"Tohmajärvi","maakunta":"Pohjois-Karjala","seutukunta":"Keski-Karjalan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"849","nimi_fi":"Toholampi","nimi_se":"Toholampi","maakunta":"Keski-Pohjanmaa","seutukunta":"Kaustisen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"850","nimi_fi":"Toivakka","nimi_se":"Toivakka","maakunta":"Keski-Suomi","seutukunta":"Jyväskylän","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"851","nimi_fi":"Tornio","nimi_se":"Torneå","maakunta":"Lappi","seutukunta":"Kemi-Tornion","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"853","nimi_fi":"Turku","nimi_se":"Åbo","maakunta":"Varsinais-Suomi","seutukunta":"Turun","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"857","nimi_fi":"Tuusniemi","nimi_se":"Tuusniemi","maakunta":"Pohjois-Savo","seutukunta":"Koillis-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"858","nimi_fi":"Tuusula","nimi_se":"Tusby","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"859","nimi_fi":"Tyrnävä","nimi_se":"Tyrnävä","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"886","nimi_fi":"Ulvila","nimi_se":"Ulvsby","maakunta":"Satakunta","seutukunta":"Porin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"887","nimi_fi":"Urjala","nimi_se":"Urjala","maakunta":"Pirkanmaa","seutukunta":"Etelä-Pirkanmaan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"889","nimi_fi":"Utajärvi","nimi_se":"Utajärvi","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Oulunkaaren","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"890","nimi_fi":"Utsjoki","nimi_se":"Utsjoki","maakunta":"Lappi","seutukunta":"Pohjois-Lapin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"892","nimi_fi":"Uurainen","nimi_se":"Uurainen","maakunta":"Keski-Suomi","seutukunta":"Jyväskylän","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"893","nimi_fi":"Uusikaarlepyy","nimi_se":"Nykarleby","maakunta":"Pohjanmaa","seutukunta":"Jakobstadsregionen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"895","nimi_fi":"Uusikaupunki","nimi_se":"Nystad","maakunta":"Varsinais-Suomi","seutukunta":"Vakka-Suomen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"785","nimi_fi":"Vaala","nimi_se":"Vaala","maakunta":"Kainuu","seutukunta":"Kajaanin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"905","nimi_fi":"Vaasa","nimi_se":"Vasa","maakunta":"Pohjanmaa","seutukunta":"Vaasan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"908","nimi_fi":"Valkeakoski","nimi_se":"Valkeakoski","maakunta":"Pirkanmaa","seutukunta":"Etelä-Pirkanmaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"911","nimi_fi":"Valtimo","nimi_se":"Valtimo","maakunta":"Pohjois-Karjala","seutukunta":"Pielisen-Karjalan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"092","nimi_fi":"Vantaa","nimi_se":"Vanda","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"915","nimi_fi":"Varkaus","nimi_se":"Varkaus","maakunta":"Pohjois-Savo","seutukunta":"Varkauden","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"918","nimi_fi":"Vehmaa","nimi_se":"Vehmaa","maakunta":"Varsinais-Suomi","seutukunta":"Vakka-Suomen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"921","nimi_fi":"Vesanto","nimi_se":"Vesanto","maakunta":"Pohjois-Savo","seutukunta":"Sisä-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"922","nimi_fi":"Vesilahti","nimi_se":"Vesilahti","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"924","nimi_fi":"Veteli","nimi_se":"Vetil","maakunta":"Keski-Pohjanmaa","seutukunta":"Kaustisen","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"925","nimi_fi":"Vieremä","nimi_se":"Vieremä","maakunta":"Pohjois-Savo","seutukunta":"Ylä-Savon","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"927","nimi_fi":"Vihti","nimi_se":"Vichtis","maakunta":"Uusimaa","seutukunta":"Helsingin","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"931","nimi_fi":"Viitasaari","nimi_se":"Viitasaari","maakunta":"Keski-Suomi","seutukunta":"Saarijärven-Viitasaaren","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"934","nimi_fi":"Vimpeli","nimi_se":"Vimpeli","maakunta":"Etelä-Pohjanmaa","seutukunta":"Järviseudun","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"935","nimi_fi":"Virolahti","nimi_se":"Virolahti","maakunta":"Kymenlaakso","seutukunta":"Kotka-Haminan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"936","nimi_fi":"Virrat","nimi_se":"Virdois","maakunta":"Pirkanmaa","seutukunta":"Ylä-Pirkanmaan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"941","nimi_fi":"Vårdö","nimi_se":"Vårdö","maakunta":"Ahvenanmaa","seutukunta":"Ålands skärgård","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"946","nimi_fi":"Vöyri","nimi_se":"Vörå","maakunta":"Pohjanmaa","seutukunta":"Vaasan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"976","nimi_fi":"Ylitornio","nimi_se":"Övertorneå","maakunta":"Lappi","seutukunta":"Torniolaakson","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"977","nimi_fi":"Ylivieska","nimi_se":"Ylivieska","maakunta":"Pohjois-Pohjanmaa","seutukunta":"Ylivieskan","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"980","nimi_fi":"Ylöjärvi","nimi_se":"Ylöjärvi","maakunta":"Pirkanmaa","seutukunta":"Tampereen","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"981","nimi_fi":"Ypäjä","nimi_se":"Ypäjä","maakunta":"Kanta-Häme","seutukunta":"Forssan","kuntamuoto":"Muu kunta"},
{"kuntakoodi":"989","nimi_fi":"Ähtäri","nimi_se":"Etseri","maakunta":"Etelä-Pohjanmaa","seutukunta":"Kuusiokuntien","kuntamuoto":"Kaupunki"},
{"kuntakoodi":"992","nimi_fi":"Äänekoski","nimi_se":"Äänekoski","maakunta":"Keski-Suomi","seutukunta":"Äänekosken","kuntamuoto":"Kaupunki"}
]